PracticaMvcCore2CM/Controllers/LibrosController.cs
using Microsoft.AspNetCore.Mvc;
using PracticaMvcCore2CM.Extensions;
using PracticaMvcCore2CM.Filters;
using PracticaMvcCore2CM.Models;
using PracticaMvcCore2CM.Repositories;

namespace PracticaMvcCore2CM.Controllers
{
    public class LibrosController : Controller
    {
        private RepositoryLibros repo;

        public LibrosController(RepositoryLibros repo)
        {
            this.repo = repo;
        }

        public IActionResult Libros(int? posicion)
        {
            if (posicion == null)
            {
                posicion = 0;
            }
            int numeroLibros = 0;
            Libro libro = this.repo.GetLibrosPaginados
                (posicion.Value, ref numeroLibros);
            ViewData["DATOS"] = "Libros " + (posicion + 1)
                + " de " + numeroLibros;
            int siguiente = posicion.Value + 1;
            if (siguiente >= numeroLibros)
            {
                siguiente = 0;
            }
            int anterior = posicion.Value - 1;
            if (anterior < 0)
            {
                anterior = numeroLibros - 1;
            }
            ViewData["SIGUIENTE"] = siguiente;
            ViewData["ANTERIOR"] = anterior;
            return View(libro);

        }

        public IActionResult LibrosPorGenero(int idgenero)
        {
            List<Libro> libros = this.repo.GetLibrosGenero(idgenero);
            return View(libros);
        }

        //[AuthorizeUsuarios]
        public IActionResult DetallesLibros(int idlibro, int? idcarrito)
        {
            if (idcarrito != null)
            {
                List<int> carrito;
                if (HttpContext.Session.GetObject<List<int>>("CARRITO") == null)
                {
                    carrito = new List<int>();
                }
                else
                {
                    carrito = HttpContext.Session.GetObject<List<int>>("CARRITO");
                }
                carrito.Add(idcarrito.Value);
                HttpContext.Session.SetObject("CARRITO", carrito);
            }
            Libro libro = this.repo.FindLibro(idlibro);
            return View(libro);
        }

        public IActionResult ProductosCarrito(int? ideliminar)
        {
            List<int> idsCarrito =
                HttpContext.Session.GetObject<List<int>>("CARRITO");
            if (idsCarrito == null)
            {
                ViewData["MENSAJE"] = "No existen libros en carrito";
                return View();
            }
            else
            {
                if (ideliminar != null)
                {
                    idsCarrito.Remove(ideliminar.Value);
                    if (idsCarrito.Count == 0)
                    {
                        HttpContext.Session.Remove("CARRITO");
                    }
                    else
                    {
                        HttpContext.Session.SetObject("CARRITO", idsCarrito);
                    }
                }
                List<Libro> libros = this.repo.GetLibrosSession(idsCarrito);
                return View(libros);
            }
        }

        [AuthorizeUsuarios]
        public async Task<IActionResult> PedidosRealizados(int idusuario, int idlibro)
        {
            //INSERTAMOS EN PEDIDOS TODO LO DE SESSION
            //LIMPIAMOS SESSION

            //MUESTRAS LA VISTA DE SQL VISTA PEDIDOS CON UN WHERE DEL USUARIO

            idusuario = int.Parse(HttpContext.User.FindFirst("Id")?.Value);
            await this.repo.AgregarProductoAsync(idlibro, idusuario);
            List<VistaPedido> pedidos = this.repo.GetPedidos(idlibro);
            return View(pedidos);
        }
    }
}

PracticaMvcCore2CM/Controllers/ManagedController.cs
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Mvc;
using PracticaMvcCore2CM.Models;
using PracticaMvcCore2CM.Repositories;
using System.Security.Claims;

namespace PracticaMvcCore2CM.Controllers
{
    public class ManagedController : Controller
    {
        private RepositoryUsuarios repo;

        public ManagedController(RepositoryUsuarios repo)
        {
            this.repo = repo;
        }

        public IActionResult DetallesUsuario(int idusuario)
        {
            //idusuario = int.Parse(HttpContext.User.FindFirst("Id")?.Value);
            Usuario user = this.repo.FindUsuario(idusuario);
            return View(user);
        }

        public IActionResult Login()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Login(string email
            , string password)
        {
            Usuario usuario =
                await this.repo.ExisteUsuario(email, password);
            if (usuario != null)
            {
                ClaimsIdentity identity =
               new ClaimsIdentity
               (CookieAuthenticationDefaults.AuthenticationScheme
               , ClaimTypes.Name, ClaimTypes.Role);
                identity.AddClaim
                    (new Claim(ClaimTypes.Name, usuario.Email));
                identity.AddClaim
                    (new Claim(ClaimTypes.NameIdentifier, usuario.Pass.ToString()));
                identity.AddClaim
                    (new Claim("Nombre", usuario.Nombre));
                identity.AddClaim
                    (new Claim("Foto", usuario.Foto.ToString()));
                identity.AddClaim
                    (new Claim("Id", usuario.IdUsuario.ToString()));

                ClaimsPrincipal user = new ClaimsPrincipal(identity);
                await HttpContext.SignInAsync
                    (CookieAuthenticationDefaults.AuthenticationScheme
                    , user);
                return RedirectToAction("Index", "Home");
            }
            else
            {
                ViewData["MENSAJE"] = "Usuario/Password incorrectos";
                return View();
            }
        }

        public async Task<IActionResult> LogOut()
        {
            await HttpContext.SignOutAsync
                (CookieAuthenticationDefaults.AuthenticationScheme);
            return RedirectToAction("Index", "Home");
        }

        public IActionResult ErrorAcceso()
        {
            return View();
        }
    }
}

PracticaMvcCore2CM/ViewComponents/MenuGenerosViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using PracticaMvcCore2CM.Models;
using PracticaMvcCore2CM.Repositories;

namespace PracticaMvcCore2CM.ViewComponents
{
    public class MenuGenerosViewComponent: ViewComponent
    {
        private RepositoryGeneros repo;

        public MenuGenerosViewComponent(RepositoryGeneros repo)
        {
            this.repo = repo;
        }

        public async Task<IViewComponentResult> InvokeAsync()
        {
            List<Genero> generos = this.repo.GetGeneros();
            return View(generos);
        }
    }
}

PracticaMvcCore2CM/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - PracticaMvcCore2CM</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/PracticaMvcCore2CM.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">PracticaMvcCore2CM</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Libros" asp-action="Libros">Libros</a>
                        </li>
                        @await Component.InvokeAsync("MenuGeneros")
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Libros" asp-action="ProductosCarrito">Carrito</a>
                        </li>
                        <partial name="_MenuUsuario" />
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - PracticaMvcCore2CM - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

PracticaMvcCore2CM/Views/Shared/_MenuUsuario.cshtml
@if (Context.User.Identity.IsAuthenticated == false)
{
    <li class="nav-item" style="text-align: right">
        <a class="nav-link text-dark" asp-area="" asp-controller="Managed" asp-action="Login">Login</a>
    </li>
}
else
{

    <li class="nav-item">
        <a asp-controller="Managed" asp-action="DetallesUsuario" asp-route-idusuario="@Context.User.FindFirst("Id")?.Value">
            <img src="~/images/@Context.User.FindFirst("Foto")?.Value" class="rounded" width="50" height="50"/>
            <label>Hola, @Context.User.FindFirst("Nombre")?.Value</label>
        </a>
    </li>
    <li class="nav-item">
        <a class="nav-link text-dark"
            asp-controller="Managed" 
            asp-action="LogOut">
           Cerrar Sesion
        </a>
    </li>
}